WptsExtensions.dll + cdpsgshims.dll
wietze/HijackLibs pull request #5
Opened 2022-08-16 06:29 UTC by k4nfr3

2022-08-22 22:27 UTC, wietze requested changes
I've added a few comments, hopefully they make sense. Let me know if you need my help.

2022-08-22 22:27 UTC, wietze commented on yml/microsoft/built-in/wptsextensions.yml
> +  - Path: 'Task Scheduler'
this would imply `%SYSTEM32%\svchost.exe` on modern Windows versions, am I right? That's also what's visible in the screenshot in the linked blog.

2022-08-22 22:27 UTC, wietze commented on yml/microsoft/built-in/wptsextensions.yml
> +    Type: Environment Variable
I think this is actually Phantom DLL Hijacking, reading the blog more closely. It ends up checking %PATH% because the DLL does not exist at all

2022-08-22 22:27 UTC, wietze commented on yml/microsoft/built-in/wptsextensions.yml
> +  - "https://itm4n.github.io/windows-dll-hijacking-clarified/"
Probably better to use the original resource instead: http://remoteawesomethoughts.blogspot.com/2019/05/windows-10-task-schedulerservice.html

2022-08-22 22:27 UTC, wietze commented on yml/microsoft/built-in/cdpsgshims.yml
> +  - "https://itm4n.github.io/windows-dll-hijacking-clarified/"
Did you mean this link instead? https://itm4n.github.io/cdpsvc-dll-hijacking/

2022-08-22 22:27 UTC, wietze commented on yml/microsoft/built-in/cdpsgshims.yml
> +    Type: Environment Variable
Similar to the previous entry, this seems to be Phantom DLL hijacking.

2022-10-26 08:00 UTC, wietze commented
Hey @k4nfr3 , if you have time to address the above issues that would be great. Thanks

2022-10-26 08:53 UTC, k4nfr3 commented
Hi, 

this is now changed as requested
Regards

2022-10-26 09:56 UTC, wietze approved these changes
Thanks for your contribution

2022-10-26 09:56 UTC, merged